#! /usr/bin/env bash

latest_available()
{
	url="https://rakudo.org/latest/star/source"
	release=$(curl -Is "$url" | grep Content-Disposition | perl -pe 's/.*(\d{4}\.\d{2}).*/\1/')

	printf -- "%s" "$release"
}

export -f latest_available
