#! /usr/bin/env bash

latest_available()
{
	url="https://rakudostar.com/latest/star/source"
	buffer=$(mktemp)

	curl -IL "$url" > "$buffer"

	release=$(grep -i Content-Disposition < "$buffer" | perl -pe 's/.*(\d{4}\.\d{2}).*/\1/')

	if [ -n "$LONESTAR_TEST" ]
	then
		cat "$buffer" >&2
	fi

	printf -- "%s" "$release"
}

export -f latest_available
