#! /usr/bin/env sh

main()
{
	version=${1:-$(find_last_version)}
	rakudo="$RAKUDO_ROOT/rakudo-star-$version"

	if [ ! -d "$rakudo" ]
	then
		printf -- "%s\n" "Rakudo Star $version is not installed" >&2
		exit 1
	fi

	printf -- 'export PATH="%s:$PATH"\n' "$rakudo"
}

find_last_version()
{
	tmp=$(mktemp)

	find "$HOME/.rakudo" -maxdepth 1 -type d > "$tmp"
	version=$(sort -h "$tmp" | tail -n 1 | awk -F- '{ print $NF }')

	rm -- "$tmp"

	printf -- "%s" "$version"
}

main "$@"
