#! /usr/bin/env sh

use "find-last-version"

main()
{
	version=${1:-$(find_last_version)}

	if [ "$version" = "" ]
	then
		printf -- "%s\n" "No Rakudo Star could be found at $RAKUDO_ROOT" >&2
		exit 2
	fi

	rakudo="$RAKUDO_ROOT/rakudo-star-$version"

	if [ ! -d "$rakudo" ]
	then
		printf -- "%s\n" "Rakudo Star $version is not installed" >&2
		exit 1
	fi

	printf -- 'export PATH="%s:$PATH"\n' "$rakudo"
}

main "$@"
