#! /usr/bin/env bash

use "latest_installed"

main()
{
	version=${1:-$(latest_installed)}

	if [ "$version" = "" ]
	then
		printf -- "%s\n" "No Rakudo Star could be found at $RAKUDO_ROOT" >&2
		exit 2
	fi

	rakudo="$RAKUDO_ROOT/rakudo-star-$version"

	if [ ! -d "$rakudo" ]
	then
		printf -- "%s\n" "Rakudo Star $version is not installed" >&2
		exit 1
	fi

	printf -- 'export PATH="%s/install/bin:$PATH"\n' "$rakudo"
	printf -- 'export PATH="%s/install/share/perl6/site/bin:$PATH"\n' "$rakudo"
}

main "$@"
