#! /usr/bin/env bash

use "build"
use "fetch_src"
use "latest_available"

main()
{
	version=${1:-$(latest_available)}

	if [ -d "$RAKUDO_ROOT/rakudo-star-$version" ]
	then
		printf -- "%s\n" "Rakudo Star sources for $version already exist"
		return 0
	fi

	fetch_src "$version"
	build     "$version"

	printf -- "%s\n" "Installation of Rakudo Star $version succesful!"
}

main "$@"
