#! /usr/bin/env bash

use "latest_installed"

main()
{
	version=${1:-$(latest_installed)}

	if [ "$version" = "" ]
	then
		printf -- "%s\n" "No Rakudo Star could be found at $RAKUDO_ROOT" >&2
		exit 2
	fi

	rakudo="$RAKUDO_ROOT/rakudo-star-$version"

	printf -- "%s" "$rakudo"
}

main "$@"

