#! /usr/bin/env bash

use "build"
use "fetch_src"
use "latest_available"

main()
{
	version=$(latest_available "${1:-latest}")

	fetch_src "$version"
	build     "$version"

	printf -- "%s\n" "Installation of Rakudo Star $version succesful!"
}

main "$@"
